#!/bin/sh
BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" = "main" ]; then
  echo "Вы не можете коммитить напрямую в ветку main. Пожалуйста, создайте новую ветку и сделайте коммит в нее."
  exit 1
fi
